spring :
  profiles:
    active: local #default 설정
    group:
      local:
        - common
      prod:
        - common

---
spring :
  config:
    activate:
      on-profile: common
# ...
---
spring :
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/pharmacy-recommendation
    username: ${SPRING_DATASOUCRE_USERNAME}
    password: ${SPRING_DATASOUCRE_PASSWORD}
  redis :
    host : localhost
    port : 6379
  jpa :
    hibernate:
      ddl-auto: create
---
spring:
  config:
    activate:
      on-profile: prod